/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 * 
 * Interactive Arctic Vehicles Dataset & Fleet Specifications
 * National Centre for Polar and Ocean Research (NCPOR) / MoES
 * Smart India Hackathon 2026 - PS 26060 - Team HackFinity
 */

import { VehicleDefinition } from './types';

export const POLAR_FLEET: Record<string, VehicleDefinition> = {
  'pb-01': {
    id: 'pb-01',
    name: 'PistenBully PB-01 (Kässbohrer 300 Polar)',
    model: 'Polar 300 Heavy Traverse Snow Groomer',
    station: 'maitri',
    category: 'Heavy Traverse Machinery',
    status: 'OPERATIONAL',
    fuelLevelPct: 82,
    engineHours: 1240,
    lastServiceDaysAgo: 18,
    nextServiceHours: 62,
    driverName: 'Tenzing Norbu (Traverse Pilot)',
    bladeCondition: 'GOOD (Hydraulics Re-Bled)',
    trackConditionPct: 78,
    cargoManifest: ['Survival Rations (72h)', 'Spares Crate #4', 'HF Emergency Dipole'],
    position: [18, 1.8, 25],
    rotationY: 0.4,
    isEngineRunning: false
  },
  'pb-02': {
    id: 'pb-02',
    name: 'PistenBully PB-02 (Heavy Cargo Winch)',
    model: 'Polar 300W with 4.5-Tonne Active Winch',
    station: 'maitri',
    category: 'Heavy Traverse Machinery',
    status: 'STANDBY',
    fuelLevelPct: 91,
    engineHours: 980,
    lastServiceDaysAgo: 8,
    nextServiceHours: 120,
    driverName: 'Col. K. R. Sharma (Logistics Lead)',
    bladeCondition: 'EXCELLENT',
    trackConditionPct: 88,
    cargoManifest: ['Fuel Sledge #2 Tow Rig', 'Synthetic Tow Strops (120 kN)'],
    position: [-24, 1.8, 28],
    rotationY: -0.6,
    isEngineRunning: false
  },
  'pb-03': {
    id: 'pb-03',
    name: 'PistenBully PB-03 (Larsemann Ice Scout)',
    model: 'Polar 300 All-Terrain',
    station: 'bharati',
    category: 'Heavy Traverse Machinery',
    status: 'OPERATIONAL',
    fuelLevelPct: 76,
    engineHours: 1420,
    lastServiceDaysAgo: 12,
    nextServiceHours: 80,
    driverName: 'Arunav Mukherjee',
    bladeCondition: 'GOOD',
    trackConditionPct: 72,
    cargoManifest: ['Glaciological Radar Antennas', 'Steam Ice Drill Rig'],
    position: [22, 1.8, 30],
    rotationY: 0.2,
    isEngineRunning: true
  },
  'sm-01': {
    id: 'sm-01',
    name: 'Snowmobile SM-01 (Ski-Doo Expedition 900)',
    model: 'BRP Rotax 900 ACE Turbo Arctic Spec',
    station: 'maitri',
    category: 'Snowmobile',
    status: 'STANDBY',
    fuelLevelPct: 68,
    engineHours: 340,
    lastServiceDaysAgo: 5,
    nextServiceHours: 160,
    driverName: 'Dr. Ananya Sen',
    trackConditionPct: 85,
    cargoManifest: ['GPS Rover Tripod', 'Nansen Supply Sledge'],
    position: [12, 0.8, 18],
    rotationY: 0.8,
    isEngineRunning: false
  },
  'sm-02': {
    id: 'sm-02',
    name: 'Snowmobile SM-02 (Arctic Cat Bearcat 7000)',
    model: 'Yamaha 1049cc 4-Stroke Utility',
    station: 'bharati',
    category: 'Snowmobile',
    status: 'OPERATIONAL',
    fuelLevelPct: 84,
    engineHours: 215,
    lastServiceDaysAgo: 14,
    nextServiceHours: 185,
    driverName: 'Dr. Meenakshi Sundaram',
    trackConditionPct: 92,
    cargoManifest: ['Atmospheric Air Sampler Kits'],
    position: [15, 0.8, 24],
    rotationY: -0.3,
    isEngineRunning: false
  },
  'tc-01': {
    id: 'tc-01',
    name: 'Tracked Carrier TC-01 (Hägglunds Bv206)',
    model: 'BAE Systems Bv206 Articulated Amphibious',
    station: 'bharati',
    category: 'Amphibious Tracked Carrier',
    status: 'IN TRANSIT',
    fuelLevelPct: 72,
    engineHours: 2180,
    lastServiceDaysAgo: 24,
    nextServiceHours: 76,
    driverName: 'Traverse Unit Bravo',
    trackConditionPct: 80,
    cargoManifest: ['1,200 kg Scientific Payloads', 'Potable Water Tank Skid', 'Medical Survival Packs'],
    position: [-38, 1.6, 12],
    rotationY: 0.0,
    isEngineRunning: true
  },
  'heli-01': {
    id: 'heli-01',
    name: 'Helicopter HELI-01 (Basler Polar Air Support)',
    model: 'Bell 412EP Polar Utility Helicopter',
    station: 'maitri',
    category: 'Aviation Support',
    status: 'STANDBY',
    fuelLevelPct: 85,
    engineHours: 2340,
    lastServiceDaysAgo: 6,
    nextServiceHours: 110,
    driverName: 'Capt. V. K. Malhotra (Chief Pilot)',
    trackConditionPct: 100,
    cargoManifest: ['Search & Rescue Trauma Litters', 'Aviation Jet A-1 Auxiliary Tank (450L)'],
    position: [55, 1.2, -25],
    rotationY: 0.0,
    isEngineRunning: false
  },
  'zb-01': {
    id: 'zb-01',
    name: 'Zodiac Boat ZB-01 (Milpro Heavy-Duty Shore Craft)',
    model: 'Zodiac Milpro MK5 HD with Yamaha 70HP Subzero',
    station: 'bharati',
    category: 'Marine Coastal',
    status: 'OPERATIONAL',
    fuelLevelPct: 60,
    engineHours: 120,
    lastServiceDaysAgo: 4,
    nextServiceHours: 80,
    driverName: 'Larsemann Marine Cell',
    trackConditionPct: 100,
    cargoManifest: ['Seabed Core Sampler', 'Life Jackets & Thermal Drysuits (6x)'],
    position: [-45, 0.5, 35],
    rotationY: 0.6,
    isEngineRunning: false
  }
};
